name: Feature Request
description: Request an enhancement for nougat.nvim
title: ":hammer_and_wrench: "
labels: []
projects: []
assignees: []
body:
  - type: checkboxes
    attributes:
      label: Did you check the docs and existing issues?
      description: Make sure you checked all of the below before submitting a feature request
      options:
        - label: I am using latest nougat.nvim
          required: true
        - label: I have read all the nougat.nvim docs
          required: true
        - label: I have searched the existing issues of nougat.nvim
          required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: Problem
      description: Describe the problem you are facing.

  - type: textarea
    validations:
      required: true
    attributes:
      label: Solution
      description: Describe the feature or behavior you would like to have.

  - type: textarea
    validations:
      required: false
    attributes:
      label: Alternatives
      description: Describe the alternative solutions or features you've considered.

  - type: textarea
    validations:
      required: false
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
